# SPDX-License-Identifier: GPL-2.0
i3c-y				:= device.o master.o
obj-$(CONFIG_I3C)		+= i3c.o
obj-$(CONFIG_I3CDEV)		+= i3cdev.o
obj-$(CONFIG_I3C)		+= master/
obj-$(CONFIG_I3C)		+= mctp/
obj-$(CONFIG_I3C_MUX_IMX3102) 	+= i3c-mux-imx3102.o
obj-$(CONFIG_RTS490XA_I3C_HUB)	+= rts490xa-i3c-hub.o
